site:
  # set the domain with schema but without trailing slash:
  domain: 'https://github.com/tshzhu/magic'
  title: Tansheng Zhu's Notes
  description: Notes for Machine Learning Theory
  keywords: machine learning, deep learning, mathematics, theory
  theme: default
  language: en-US
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  root-path: /magic
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  # navigation is unused (header removed); keep minimal config for books/blogs only
  git:
    base-url: https://github.com/tshzhu/magic/blob/main/source
  contact:
    name: Tansheng Zhu
    homepage: https://tshzhu.github.io
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    # comment:
      # provider: disqus
      # name: gitsite
    # analytics:
      # provider: google
      # gtag: G-5Z40K7NBL5

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - robots.txt
    - ads.txt

# you can add any items:
