site:
  # set the domain with schema but without trailing slash:
  domain: 'https://github.com/tshzhu/magic'
  title: Magic
  description: Notes for Machine Learning Theory
  keywords: machine learning, deep learning, mathematics, theory
  theme: default
  language: en-US
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  navigation:
    - title: License
      uri: /pages/license/index.html
    - title: Discuss
      uri: https://github.com/michaelliao/gitsite/discussions
      external: true
  git:
    base-url: https://github.com/michaelliao/gitsite/blob/main/source
  contact:
    name: Tansheng Zhu
    github: https://github.com/tshzhu
    twitter: https://twitter.com/tanshengzhu
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: false
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    # comment:
      # provider: disqus
      # name: gitsite
    # analytics:
      # provider: google
      # gtag: G-5Z40K7NBL5

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
